/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:81e85c04-867d-4fd5-8359-2eb8989cec8f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ftL7CyxAt",
    "aws_user_pools_web_client_id": "393nhfh6t33djqd8t9v4jupvc0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mead4g5zrjgeti3uslue3i6ali.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jbbgq2hpa5dx5prv6ylacljuqu",
    "aws_user_files_s3_bucket": "diplomacyscholarsassde8bb8281bda44b9858c32f03ac164338-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
